repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [ python ]

      - id: autoflake
        name: autoflake
        entry: autoflake
        language: system
        types: [ python ]
        args: [ --in-place, --remove-all-unused-imports, --remove-duplicate-keys ]

      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        args: [
           "--ignore=E203,W503,FI10,FI11,FI12,FI13,FI14,FI15,FI16,FI17,FI58,PT013",
           "--max-line-length=200",
           "--per-file-ignores=tests/*.py:S101"
        ]

      - id: isort
        name: isort
        entry: isort
        language: system
        types: [ python ]

      - id: ruff
        name: ruff
        entry: ruff check
        language: system
        types: [ python ]