name: likes

services:
  likes-backend:
    build: 
      context: src
    expose:
      - "8000"
    env_file:
      - ./.env
    healthcheck:
      test: curl --fail http://localhost:8000/healthcheck || exit 1
      interval: 10s
      retries: 5
      timeout: 2s
    networks:
      - movies-net
    restart: always
    profiles: [likes]

  likes-mongodb:
    image: mongo
    expose:
      - "27017"
    restart: unless-stopped
    volumes:
      - likes-db-mongo:/data/db:rw
      - likes-cfg-mongo:/data/configdb:rw
    profiles: [likes]
    networks:
      - movies-net

  likes-redis:
    image: redis:7.4
    expose:
      - "6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      retries: 5
      timeout: 2s
    volumes:
      - likes-redis-volume:/data
    networks:
      - movies-net
    restart: always
    profiles: [likes]


networks:
  movies-net:

volumes:
  likes-db-mongo:
  likes-redis-volume:
  likes-cfg-mongo:
