name: elk

services:
  elasticsearch:
    image: elasticsearch:8.10.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    expose:
      - "9200"
    volumes:
      - elk-db-volume:/usr/share/elasticsearch/data
    networks:
      - movies-net
    restart: always
    profiles: [elk]

  kibana:
    image: kibana:8.10.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200 
    networks:
      - movies-net
    restart: always
    profiles: [elk]

  logstash:
    image: logstash:8.10.2
    depends_on:
      - elasticsearch
    environment:
      XPACK_MONITORING_ENABLED: "false"
      ES_HOST: "elasticsearch:9200"
    ports:
      - "5044:5044/udp"
    volumes:
      - ./logstash.conf:/config/logstash.conf:ro
    command: logstash -f /config/logstash.conf 
    networks:
      - movies-net
    restart: always
    profiles: [elk]

networks:
  movies-net:

volumes:
  elk-db-volume: