name: sentry

services:
  sentry-api:
    image: sentry:latest
    env_file:
      - .env
    depends_on:
      - sentry-db
      - sentry-redis
    ports:
      - "9000:9000"
    volumes:
      - sentry-data-volume:/var/lib/sentry/files
    networks:
      - movies-net
    profiles: [sentry]

  sentry-worker:
    image: sentry:latest
    env_file:
      - .env
    depends_on:
      - sentry-db
      - sentry-redis
    command: sentry run worker
    networks:
      - movies-net
    profiles: [sentry]

  sentry-cron:
    image: sentry:latest
    env_file:
      - .env
    depends_on:
      - sentry-db
      - sentry-redis
    command: sentry run cron
    networks:
      - movies-net
    profiles: [sentry]

  sentry-db:
    image: postgres:latest
    expose:
      - "5432"
    env_file:
      - .env
    volumes:
      - sentry-db-volume:/var/lib/postgresql/data
    networks:
      - movies-net
    profiles: [sentry]

  sentry-redis:
    image: redis:latest
    expose:
      - "6379"
    networks:
      - movies-net
    restart: always
    profiles: [sentry]

networks:
  movies-net:

volumes:
  sentry-data-volume:
  sentry-db-volume:
  sentry-redis-volume:
